version: '3'
services:
  phpmyadmin:
    image: phpmyadmin:5.1.1-apache
    restart: always
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    networks:
      - proxynet
  mysql:
    build: 
      context: ./docker/mysql
    volumes:
      - ./var/mysql/data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/setup.sql
    command: --sql_mode="" --default-authentication-plugin=mysql_native_password
    user: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uroot", "-p${DATABASE_ROOT_PASSWORD}", "-hmysql", "--silent" ]
    env_file:
      - .env
    networks:
      - proxynet
  source:
    build:
      context: ./docker/php/php8.2-apiline
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    restart: always
    volumes:
      - ./src:/src
    user: www-data:www-data
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - proxynet

  nginx:
    build:
      context: ./docker/nginx
      args:
          USER_ID: ${USER_ID:-0}
          GROUP_ID: ${GROUP_ID:-0}
    restart: always
    volumes:
      - ./src:/src
      - ./docker/nginx/certs:/etc/nginx/certs
    ports:
      - ${EXTERNAL_WEB_PORT}:80
      - 443:443
    env_file:
      - .env
    networks:
      - proxynet

  # vue:
  #   build: 
  #     context: ./docker/node
  #   volumes:
  #     - ./src/frontend/vuejs:/app
  #   command: ["yarn", "run", "dev"]
  #   depends_on:
  #     - source
  #   networks:
  #     - proxynet
  #   ports:
  #     - "8989:8080"

networks:
  proxynet:
    name: custom_network